version: '3.4'

services:

  web:
    image: frontend-web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 3000:3000
    networks:
      - ituy_network

  api-gateway:
    image: backend-api-gateway
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - 4000:4000
    networks:
      - ituy_network
    # environment:
    #   ENVIRONMENT: 'production'
    #   PATH_UPLOADS: '/usr/src/ituee/uploads'
      
networks:
  ituy_network:
